version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eventabee-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventabee
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: eventabee-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data: